import type { AuthConfig } from "convex/server";

export default {
  providers: [
    {
      // Must match the issuer in JWT tokens generated by Better Auth
      domain: "http://localhost:5173",
      applicationID: "convex",
    },
  ],
} satisfies AuthConfig;
