/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BoardsRouteImport } from './routes/boards'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoardsIndexRouteImport } from './routes/boards.index'
import { Route as BoardsBoardIdRouteImport } from './routes/boards.$boardId'
import { Route as BoardsBoardIdIndexRouteImport } from './routes/boards.$boardId.index'
import { Route as BoardsBoardIdCardsCardSlugRouteImport } from './routes/boards.$boardId.cards.$cardSlug'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsRoute = BoardsRouteImport.update({
  id: '/boards',
  path: '/boards',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsIndexRoute = BoardsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BoardsRoute,
} as any)
const BoardsBoardIdRoute = BoardsBoardIdRouteImport.update({
  id: '/$boardId',
  path: '/$boardId',
  getParentRoute: () => BoardsRoute,
} as any)
const BoardsBoardIdIndexRoute = BoardsBoardIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BoardsBoardIdRoute,
} as any)
const BoardsBoardIdCardsCardSlugRoute =
  BoardsBoardIdCardsCardSlugRouteImport.update({
    id: '/cards/$cardSlug',
    path: '/cards/$cardSlug',
    getParentRoute: () => BoardsBoardIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boards': typeof BoardsRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/boards/$boardId': typeof BoardsBoardIdRouteWithChildren
  '/boards/': typeof BoardsIndexRoute
  '/boards/$boardId/': typeof BoardsBoardIdIndexRoute
  '/boards/$boardId/cards/$cardSlug': typeof BoardsBoardIdCardsCardSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/boards': typeof BoardsIndexRoute
  '/boards/$boardId': typeof BoardsBoardIdIndexRoute
  '/boards/$boardId/cards/$cardSlug': typeof BoardsBoardIdCardsCardSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boards': typeof BoardsRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/boards/$boardId': typeof BoardsBoardIdRouteWithChildren
  '/boards/': typeof BoardsIndexRoute
  '/boards/$boardId/': typeof BoardsBoardIdIndexRoute
  '/boards/$boardId/cards/$cardSlug': typeof BoardsBoardIdCardsCardSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boards'
    | '/login'
    | '/profile'
    | '/register'
    | '/boards/$boardId'
    | '/boards/'
    | '/boards/$boardId/'
    | '/boards/$boardId/cards/$cardSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/profile'
    | '/register'
    | '/boards'
    | '/boards/$boardId'
    | '/boards/$boardId/cards/$cardSlug'
  id:
    | '__root__'
    | '/'
    | '/boards'
    | '/login'
    | '/profile'
    | '/register'
    | '/boards/$boardId'
    | '/boards/'
    | '/boards/$boardId/'
    | '/boards/$boardId/cards/$cardSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardsRoute: typeof BoardsRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards': {
      id: '/boards'
      path: '/boards'
      fullPath: '/boards'
      preLoaderRoute: typeof BoardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards/': {
      id: '/boards/'
      path: '/'
      fullPath: '/boards/'
      preLoaderRoute: typeof BoardsIndexRouteImport
      parentRoute: typeof BoardsRoute
    }
    '/boards/$boardId': {
      id: '/boards/$boardId'
      path: '/$boardId'
      fullPath: '/boards/$boardId'
      preLoaderRoute: typeof BoardsBoardIdRouteImport
      parentRoute: typeof BoardsRoute
    }
    '/boards/$boardId/': {
      id: '/boards/$boardId/'
      path: '/'
      fullPath: '/boards/$boardId/'
      preLoaderRoute: typeof BoardsBoardIdIndexRouteImport
      parentRoute: typeof BoardsBoardIdRoute
    }
    '/boards/$boardId/cards/$cardSlug': {
      id: '/boards/$boardId/cards/$cardSlug'
      path: '/cards/$cardSlug'
      fullPath: '/boards/$boardId/cards/$cardSlug'
      preLoaderRoute: typeof BoardsBoardIdCardsCardSlugRouteImport
      parentRoute: typeof BoardsBoardIdRoute
    }
  }
}

interface BoardsBoardIdRouteChildren {
  BoardsBoardIdIndexRoute: typeof BoardsBoardIdIndexRoute
  BoardsBoardIdCardsCardSlugRoute: typeof BoardsBoardIdCardsCardSlugRoute
}

const BoardsBoardIdRouteChildren: BoardsBoardIdRouteChildren = {
  BoardsBoardIdIndexRoute: BoardsBoardIdIndexRoute,
  BoardsBoardIdCardsCardSlugRoute: BoardsBoardIdCardsCardSlugRoute,
}

const BoardsBoardIdRouteWithChildren = BoardsBoardIdRoute._addFileChildren(
  BoardsBoardIdRouteChildren,
)

interface BoardsRouteChildren {
  BoardsBoardIdRoute: typeof BoardsBoardIdRouteWithChildren
  BoardsIndexRoute: typeof BoardsIndexRoute
}

const BoardsRouteChildren: BoardsRouteChildren = {
  BoardsBoardIdRoute: BoardsBoardIdRouteWithChildren,
  BoardsIndexRoute: BoardsIndexRoute,
}

const BoardsRouteWithChildren =
  BoardsRoute._addFileChildren(BoardsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardsRoute: BoardsRouteWithChildren,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
