/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimeRouteImport } from './routes/time'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BoardsRouteImport } from './routes/boards'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoardsIndexRouteImport } from './routes/boards.index'
import { Route as BoardsBoardIdRouteImport } from './routes/boards.$boardId'
import { Route as BoardsBoardIdIndexRouteImport } from './routes/boards.$boardId.index'
import { Route as BoardsBoardIdSecretsRouteImport } from './routes/boards.$boardId.secrets'
import { Route as BoardsBoardIdDocsRouteImport } from './routes/boards.$boardId.docs'
import { Route as BoardsBoardIdSecretsIndexRouteImport } from './routes/boards.$boardId.secrets.index'
import { Route as BoardsBoardIdDocsIndexRouteImport } from './routes/boards.$boardId.docs.index'
import { Route as BoardsBoardIdDocsDocIdRouteImport } from './routes/boards.$boardId.docs.$docId'
import { Route as BoardsBoardIdCardsCardSlugRouteImport } from './routes/boards.$boardId.cards.$cardSlug'

const TimeRoute = TimeRouteImport.update({
  id: '/time',
  path: '/time',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsRoute = BoardsRouteImport.update({
  id: '/boards',
  path: '/boards',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsIndexRoute = BoardsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BoardsRoute,
} as any)
const BoardsBoardIdRoute = BoardsBoardIdRouteImport.update({
  id: '/$boardId',
  path: '/$boardId',
  getParentRoute: () => BoardsRoute,
} as any)
const BoardsBoardIdIndexRoute = BoardsBoardIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BoardsBoardIdRoute,
} as any)
const BoardsBoardIdSecretsRoute = BoardsBoardIdSecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => BoardsBoardIdRoute,
} as any)
const BoardsBoardIdDocsRoute = BoardsBoardIdDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => BoardsBoardIdRoute,
} as any)
const BoardsBoardIdSecretsIndexRoute =
  BoardsBoardIdSecretsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => BoardsBoardIdSecretsRoute,
  } as any)
const BoardsBoardIdDocsIndexRoute = BoardsBoardIdDocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BoardsBoardIdDocsRoute,
} as any)
const BoardsBoardIdDocsDocIdRoute = BoardsBoardIdDocsDocIdRouteImport.update({
  id: '/$docId',
  path: '/$docId',
  getParentRoute: () => BoardsBoardIdDocsRoute,
} as any)
const BoardsBoardIdCardsCardSlugRoute =
  BoardsBoardIdCardsCardSlugRouteImport.update({
    id: '/cards/$cardSlug',
    path: '/cards/$cardSlug',
    getParentRoute: () => BoardsBoardIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boards': typeof BoardsRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/time': typeof TimeRoute
  '/boards/$boardId': typeof BoardsBoardIdRouteWithChildren
  '/boards/': typeof BoardsIndexRoute
  '/boards/$boardId/docs': typeof BoardsBoardIdDocsRouteWithChildren
  '/boards/$boardId/secrets': typeof BoardsBoardIdSecretsRouteWithChildren
  '/boards/$boardId/': typeof BoardsBoardIdIndexRoute
  '/boards/$boardId/cards/$cardSlug': typeof BoardsBoardIdCardsCardSlugRoute
  '/boards/$boardId/docs/$docId': typeof BoardsBoardIdDocsDocIdRoute
  '/boards/$boardId/docs/': typeof BoardsBoardIdDocsIndexRoute
  '/boards/$boardId/secrets/': typeof BoardsBoardIdSecretsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/time': typeof TimeRoute
  '/boards': typeof BoardsIndexRoute
  '/boards/$boardId': typeof BoardsBoardIdIndexRoute
  '/boards/$boardId/cards/$cardSlug': typeof BoardsBoardIdCardsCardSlugRoute
  '/boards/$boardId/docs/$docId': typeof BoardsBoardIdDocsDocIdRoute
  '/boards/$boardId/docs': typeof BoardsBoardIdDocsIndexRoute
  '/boards/$boardId/secrets': typeof BoardsBoardIdSecretsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boards': typeof BoardsRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/time': typeof TimeRoute
  '/boards/$boardId': typeof BoardsBoardIdRouteWithChildren
  '/boards/': typeof BoardsIndexRoute
  '/boards/$boardId/docs': typeof BoardsBoardIdDocsRouteWithChildren
  '/boards/$boardId/secrets': typeof BoardsBoardIdSecretsRouteWithChildren
  '/boards/$boardId/': typeof BoardsBoardIdIndexRoute
  '/boards/$boardId/cards/$cardSlug': typeof BoardsBoardIdCardsCardSlugRoute
  '/boards/$boardId/docs/$docId': typeof BoardsBoardIdDocsDocIdRoute
  '/boards/$boardId/docs/': typeof BoardsBoardIdDocsIndexRoute
  '/boards/$boardId/secrets/': typeof BoardsBoardIdSecretsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boards'
    | '/login'
    | '/profile'
    | '/register'
    | '/time'
    | '/boards/$boardId'
    | '/boards/'
    | '/boards/$boardId/docs'
    | '/boards/$boardId/secrets'
    | '/boards/$boardId/'
    | '/boards/$boardId/cards/$cardSlug'
    | '/boards/$boardId/docs/$docId'
    | '/boards/$boardId/docs/'
    | '/boards/$boardId/secrets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/profile'
    | '/register'
    | '/time'
    | '/boards'
    | '/boards/$boardId'
    | '/boards/$boardId/cards/$cardSlug'
    | '/boards/$boardId/docs/$docId'
    | '/boards/$boardId/docs'
    | '/boards/$boardId/secrets'
  id:
    | '__root__'
    | '/'
    | '/boards'
    | '/login'
    | '/profile'
    | '/register'
    | '/time'
    | '/boards/$boardId'
    | '/boards/'
    | '/boards/$boardId/docs'
    | '/boards/$boardId/secrets'
    | '/boards/$boardId/'
    | '/boards/$boardId/cards/$cardSlug'
    | '/boards/$boardId/docs/$docId'
    | '/boards/$boardId/docs/'
    | '/boards/$boardId/secrets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardsRoute: typeof BoardsRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  TimeRoute: typeof TimeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/time': {
      id: '/time'
      path: '/time'
      fullPath: '/time'
      preLoaderRoute: typeof TimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards': {
      id: '/boards'
      path: '/boards'
      fullPath: '/boards'
      preLoaderRoute: typeof BoardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards/': {
      id: '/boards/'
      path: '/'
      fullPath: '/boards/'
      preLoaderRoute: typeof BoardsIndexRouteImport
      parentRoute: typeof BoardsRoute
    }
    '/boards/$boardId': {
      id: '/boards/$boardId'
      path: '/$boardId'
      fullPath: '/boards/$boardId'
      preLoaderRoute: typeof BoardsBoardIdRouteImport
      parentRoute: typeof BoardsRoute
    }
    '/boards/$boardId/': {
      id: '/boards/$boardId/'
      path: '/'
      fullPath: '/boards/$boardId/'
      preLoaderRoute: typeof BoardsBoardIdIndexRouteImport
      parentRoute: typeof BoardsBoardIdRoute
    }
    '/boards/$boardId/secrets': {
      id: '/boards/$boardId/secrets'
      path: '/secrets'
      fullPath: '/boards/$boardId/secrets'
      preLoaderRoute: typeof BoardsBoardIdSecretsRouteImport
      parentRoute: typeof BoardsBoardIdRoute
    }
    '/boards/$boardId/docs': {
      id: '/boards/$boardId/docs'
      path: '/docs'
      fullPath: '/boards/$boardId/docs'
      preLoaderRoute: typeof BoardsBoardIdDocsRouteImport
      parentRoute: typeof BoardsBoardIdRoute
    }
    '/boards/$boardId/secrets/': {
      id: '/boards/$boardId/secrets/'
      path: '/'
      fullPath: '/boards/$boardId/secrets/'
      preLoaderRoute: typeof BoardsBoardIdSecretsIndexRouteImport
      parentRoute: typeof BoardsBoardIdSecretsRoute
    }
    '/boards/$boardId/docs/': {
      id: '/boards/$boardId/docs/'
      path: '/'
      fullPath: '/boards/$boardId/docs/'
      preLoaderRoute: typeof BoardsBoardIdDocsIndexRouteImport
      parentRoute: typeof BoardsBoardIdDocsRoute
    }
    '/boards/$boardId/docs/$docId': {
      id: '/boards/$boardId/docs/$docId'
      path: '/$docId'
      fullPath: '/boards/$boardId/docs/$docId'
      preLoaderRoute: typeof BoardsBoardIdDocsDocIdRouteImport
      parentRoute: typeof BoardsBoardIdDocsRoute
    }
    '/boards/$boardId/cards/$cardSlug': {
      id: '/boards/$boardId/cards/$cardSlug'
      path: '/cards/$cardSlug'
      fullPath: '/boards/$boardId/cards/$cardSlug'
      preLoaderRoute: typeof BoardsBoardIdCardsCardSlugRouteImport
      parentRoute: typeof BoardsBoardIdRoute
    }
  }
}

interface BoardsBoardIdDocsRouteChildren {
  BoardsBoardIdDocsDocIdRoute: typeof BoardsBoardIdDocsDocIdRoute
  BoardsBoardIdDocsIndexRoute: typeof BoardsBoardIdDocsIndexRoute
}

const BoardsBoardIdDocsRouteChildren: BoardsBoardIdDocsRouteChildren = {
  BoardsBoardIdDocsDocIdRoute: BoardsBoardIdDocsDocIdRoute,
  BoardsBoardIdDocsIndexRoute: BoardsBoardIdDocsIndexRoute,
}

const BoardsBoardIdDocsRouteWithChildren =
  BoardsBoardIdDocsRoute._addFileChildren(BoardsBoardIdDocsRouteChildren)

interface BoardsBoardIdSecretsRouteChildren {
  BoardsBoardIdSecretsIndexRoute: typeof BoardsBoardIdSecretsIndexRoute
}

const BoardsBoardIdSecretsRouteChildren: BoardsBoardIdSecretsRouteChildren = {
  BoardsBoardIdSecretsIndexRoute: BoardsBoardIdSecretsIndexRoute,
}

const BoardsBoardIdSecretsRouteWithChildren =
  BoardsBoardIdSecretsRoute._addFileChildren(BoardsBoardIdSecretsRouteChildren)

interface BoardsBoardIdRouteChildren {
  BoardsBoardIdDocsRoute: typeof BoardsBoardIdDocsRouteWithChildren
  BoardsBoardIdSecretsRoute: typeof BoardsBoardIdSecretsRouteWithChildren
  BoardsBoardIdIndexRoute: typeof BoardsBoardIdIndexRoute
  BoardsBoardIdCardsCardSlugRoute: typeof BoardsBoardIdCardsCardSlugRoute
}

const BoardsBoardIdRouteChildren: BoardsBoardIdRouteChildren = {
  BoardsBoardIdDocsRoute: BoardsBoardIdDocsRouteWithChildren,
  BoardsBoardIdSecretsRoute: BoardsBoardIdSecretsRouteWithChildren,
  BoardsBoardIdIndexRoute: BoardsBoardIdIndexRoute,
  BoardsBoardIdCardsCardSlugRoute: BoardsBoardIdCardsCardSlugRoute,
}

const BoardsBoardIdRouteWithChildren = BoardsBoardIdRoute._addFileChildren(
  BoardsBoardIdRouteChildren,
)

interface BoardsRouteChildren {
  BoardsBoardIdRoute: typeof BoardsBoardIdRouteWithChildren
  BoardsIndexRoute: typeof BoardsIndexRoute
}

const BoardsRouteChildren: BoardsRouteChildren = {
  BoardsBoardIdRoute: BoardsBoardIdRouteWithChildren,
  BoardsIndexRoute: BoardsIndexRoute,
}

const BoardsRouteWithChildren =
  BoardsRoute._addFileChildren(BoardsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardsRoute: BoardsRouteWithChildren,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  TimeRoute: TimeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
