/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimeRouteImport } from './routes/time'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BoardsRouteImport } from './routes/boards'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoardsIndexRouteImport } from './routes/boards.index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as BoardsBoardIdRouteImport } from './routes/boards.$boardId'
import { Route as BoardsBoardIdIndexRouteImport } from './routes/boards.$boardId.index'
import { Route as BoardsBoardIdWebhooksRouteImport } from './routes/boards.$boardId.webhooks'
import { Route as BoardsBoardIdSecretsRouteImport } from './routes/boards.$boardId.secrets'
import { Route as BoardsBoardIdHtmldocsRouteImport } from './routes/boards.$boardId.htmldocs'
import { Route as BoardsBoardIdDocsRouteImport } from './routes/boards.$boardId.docs'
import { Route as BoardsBoardIdCanvasRouteImport } from './routes/boards.$boardId.canvas'
import { Route as BoardsBoardIdArchiveRouteImport } from './routes/boards.$boardId.archive'
import { Route as BoardsBoardIdWebhooksIndexRouteImport } from './routes/boards.$boardId.webhooks.index'
import { Route as BoardsBoardIdSecretsIndexRouteImport } from './routes/boards.$boardId.secrets.index'
import { Route as BoardsBoardIdHtmldocsIndexRouteImport } from './routes/boards.$boardId.htmldocs.index'
import { Route as BoardsBoardIdDocsIndexRouteImport } from './routes/boards.$boardId.docs.index'
import { Route as BoardsBoardIdCanvasIndexRouteImport } from './routes/boards.$boardId.canvas.index'
import { Route as BoardsBoardIdArchiveIndexRouteImport } from './routes/boards.$boardId.archive.index'
import { Route as BoardsBoardIdHtmldocsHtmlDocIdRouteImport } from './routes/boards.$boardId.htmldocs.$htmlDocId'
import { Route as BoardsBoardIdDocsDocIdRouteImport } from './routes/boards.$boardId.docs.$docId'
import { Route as BoardsBoardIdCardsCardSlugRouteImport } from './routes/boards.$boardId.cards.$cardSlug'
import { Route as BoardsBoardIdCanvasCanvasIdRouteImport } from './routes/boards.$boardId.canvas.$canvasId'

const TimeRoute = TimeRouteImport.update({
  id: '/time',
  path: '/time',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsRoute = BoardsRouteImport.update({
  id: '/boards',
  path: '/boards',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsIndexRoute = BoardsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BoardsRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsBoardIdRoute = BoardsBoardIdRouteImport.update({
  id: '/$boardId',
  path: '/$boardId',
  getParentRoute: () => BoardsRoute,
} as any)
const BoardsBoardIdIndexRoute = BoardsBoardIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BoardsBoardIdRoute,
} as any)
const BoardsBoardIdWebhooksRoute = BoardsBoardIdWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => BoardsBoardIdRoute,
} as any)
const BoardsBoardIdSecretsRoute = BoardsBoardIdSecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => BoardsBoardIdRoute,
} as any)
const BoardsBoardIdHtmldocsRoute = BoardsBoardIdHtmldocsRouteImport.update({
  id: '/htmldocs',
  path: '/htmldocs',
  getParentRoute: () => BoardsBoardIdRoute,
} as any)
const BoardsBoardIdDocsRoute = BoardsBoardIdDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => BoardsBoardIdRoute,
} as any)
const BoardsBoardIdCanvasRoute = BoardsBoardIdCanvasRouteImport.update({
  id: '/canvas',
  path: '/canvas',
  getParentRoute: () => BoardsBoardIdRoute,
} as any)
const BoardsBoardIdArchiveRoute = BoardsBoardIdArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => BoardsBoardIdRoute,
} as any)
const BoardsBoardIdWebhooksIndexRoute =
  BoardsBoardIdWebhooksIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => BoardsBoardIdWebhooksRoute,
  } as any)
const BoardsBoardIdSecretsIndexRoute =
  BoardsBoardIdSecretsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => BoardsBoardIdSecretsRoute,
  } as any)
const BoardsBoardIdHtmldocsIndexRoute =
  BoardsBoardIdHtmldocsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => BoardsBoardIdHtmldocsRoute,
  } as any)
const BoardsBoardIdDocsIndexRoute = BoardsBoardIdDocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BoardsBoardIdDocsRoute,
} as any)
const BoardsBoardIdCanvasIndexRoute =
  BoardsBoardIdCanvasIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => BoardsBoardIdCanvasRoute,
  } as any)
const BoardsBoardIdArchiveIndexRoute =
  BoardsBoardIdArchiveIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => BoardsBoardIdArchiveRoute,
  } as any)
const BoardsBoardIdHtmldocsHtmlDocIdRoute =
  BoardsBoardIdHtmldocsHtmlDocIdRouteImport.update({
    id: '/$htmlDocId',
    path: '/$htmlDocId',
    getParentRoute: () => BoardsBoardIdHtmldocsRoute,
  } as any)
const BoardsBoardIdDocsDocIdRoute = BoardsBoardIdDocsDocIdRouteImport.update({
  id: '/$docId',
  path: '/$docId',
  getParentRoute: () => BoardsBoardIdDocsRoute,
} as any)
const BoardsBoardIdCardsCardSlugRoute =
  BoardsBoardIdCardsCardSlugRouteImport.update({
    id: '/cards/$cardSlug',
    path: '/cards/$cardSlug',
    getParentRoute: () => BoardsBoardIdRoute,
  } as any)
const BoardsBoardIdCanvasCanvasIdRoute =
  BoardsBoardIdCanvasCanvasIdRouteImport.update({
    id: '/$canvasId',
    path: '/$canvasId',
    getParentRoute: () => BoardsBoardIdCanvasRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boards': typeof BoardsRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/time': typeof TimeRoute
  '/boards/$boardId': typeof BoardsBoardIdRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/boards/': typeof BoardsIndexRoute
  '/boards/$boardId/archive': typeof BoardsBoardIdArchiveRouteWithChildren
  '/boards/$boardId/canvas': typeof BoardsBoardIdCanvasRouteWithChildren
  '/boards/$boardId/docs': typeof BoardsBoardIdDocsRouteWithChildren
  '/boards/$boardId/htmldocs': typeof BoardsBoardIdHtmldocsRouteWithChildren
  '/boards/$boardId/secrets': typeof BoardsBoardIdSecretsRouteWithChildren
  '/boards/$boardId/webhooks': typeof BoardsBoardIdWebhooksRouteWithChildren
  '/boards/$boardId/': typeof BoardsBoardIdIndexRoute
  '/boards/$boardId/canvas/$canvasId': typeof BoardsBoardIdCanvasCanvasIdRoute
  '/boards/$boardId/cards/$cardSlug': typeof BoardsBoardIdCardsCardSlugRoute
  '/boards/$boardId/docs/$docId': typeof BoardsBoardIdDocsDocIdRoute
  '/boards/$boardId/htmldocs/$htmlDocId': typeof BoardsBoardIdHtmldocsHtmlDocIdRoute
  '/boards/$boardId/archive/': typeof BoardsBoardIdArchiveIndexRoute
  '/boards/$boardId/canvas/': typeof BoardsBoardIdCanvasIndexRoute
  '/boards/$boardId/docs/': typeof BoardsBoardIdDocsIndexRoute
  '/boards/$boardId/htmldocs/': typeof BoardsBoardIdHtmldocsIndexRoute
  '/boards/$boardId/secrets/': typeof BoardsBoardIdSecretsIndexRoute
  '/boards/$boardId/webhooks/': typeof BoardsBoardIdWebhooksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/time': typeof TimeRoute
  '/invite/$token': typeof InviteTokenRoute
  '/boards': typeof BoardsIndexRoute
  '/boards/$boardId': typeof BoardsBoardIdIndexRoute
  '/boards/$boardId/canvas/$canvasId': typeof BoardsBoardIdCanvasCanvasIdRoute
  '/boards/$boardId/cards/$cardSlug': typeof BoardsBoardIdCardsCardSlugRoute
  '/boards/$boardId/docs/$docId': typeof BoardsBoardIdDocsDocIdRoute
  '/boards/$boardId/htmldocs/$htmlDocId': typeof BoardsBoardIdHtmldocsHtmlDocIdRoute
  '/boards/$boardId/archive': typeof BoardsBoardIdArchiveIndexRoute
  '/boards/$boardId/canvas': typeof BoardsBoardIdCanvasIndexRoute
  '/boards/$boardId/docs': typeof BoardsBoardIdDocsIndexRoute
  '/boards/$boardId/htmldocs': typeof BoardsBoardIdHtmldocsIndexRoute
  '/boards/$boardId/secrets': typeof BoardsBoardIdSecretsIndexRoute
  '/boards/$boardId/webhooks': typeof BoardsBoardIdWebhooksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boards': typeof BoardsRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/time': typeof TimeRoute
  '/boards/$boardId': typeof BoardsBoardIdRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/boards/': typeof BoardsIndexRoute
  '/boards/$boardId/archive': typeof BoardsBoardIdArchiveRouteWithChildren
  '/boards/$boardId/canvas': typeof BoardsBoardIdCanvasRouteWithChildren
  '/boards/$boardId/docs': typeof BoardsBoardIdDocsRouteWithChildren
  '/boards/$boardId/htmldocs': typeof BoardsBoardIdHtmldocsRouteWithChildren
  '/boards/$boardId/secrets': typeof BoardsBoardIdSecretsRouteWithChildren
  '/boards/$boardId/webhooks': typeof BoardsBoardIdWebhooksRouteWithChildren
  '/boards/$boardId/': typeof BoardsBoardIdIndexRoute
  '/boards/$boardId/canvas/$canvasId': typeof BoardsBoardIdCanvasCanvasIdRoute
  '/boards/$boardId/cards/$cardSlug': typeof BoardsBoardIdCardsCardSlugRoute
  '/boards/$boardId/docs/$docId': typeof BoardsBoardIdDocsDocIdRoute
  '/boards/$boardId/htmldocs/$htmlDocId': typeof BoardsBoardIdHtmldocsHtmlDocIdRoute
  '/boards/$boardId/archive/': typeof BoardsBoardIdArchiveIndexRoute
  '/boards/$boardId/canvas/': typeof BoardsBoardIdCanvasIndexRoute
  '/boards/$boardId/docs/': typeof BoardsBoardIdDocsIndexRoute
  '/boards/$boardId/htmldocs/': typeof BoardsBoardIdHtmldocsIndexRoute
  '/boards/$boardId/secrets/': typeof BoardsBoardIdSecretsIndexRoute
  '/boards/$boardId/webhooks/': typeof BoardsBoardIdWebhooksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boards'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/time'
    | '/boards/$boardId'
    | '/invite/$token'
    | '/boards/'
    | '/boards/$boardId/archive'
    | '/boards/$boardId/canvas'
    | '/boards/$boardId/docs'
    | '/boards/$boardId/htmldocs'
    | '/boards/$boardId/secrets'
    | '/boards/$boardId/webhooks'
    | '/boards/$boardId/'
    | '/boards/$boardId/canvas/$canvasId'
    | '/boards/$boardId/cards/$cardSlug'
    | '/boards/$boardId/docs/$docId'
    | '/boards/$boardId/htmldocs/$htmlDocId'
    | '/boards/$boardId/archive/'
    | '/boards/$boardId/canvas/'
    | '/boards/$boardId/docs/'
    | '/boards/$boardId/htmldocs/'
    | '/boards/$boardId/secrets/'
    | '/boards/$boardId/webhooks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/time'
    | '/invite/$token'
    | '/boards'
    | '/boards/$boardId'
    | '/boards/$boardId/canvas/$canvasId'
    | '/boards/$boardId/cards/$cardSlug'
    | '/boards/$boardId/docs/$docId'
    | '/boards/$boardId/htmldocs/$htmlDocId'
    | '/boards/$boardId/archive'
    | '/boards/$boardId/canvas'
    | '/boards/$boardId/docs'
    | '/boards/$boardId/htmldocs'
    | '/boards/$boardId/secrets'
    | '/boards/$boardId/webhooks'
  id:
    | '__root__'
    | '/'
    | '/boards'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/time'
    | '/boards/$boardId'
    | '/invite/$token'
    | '/boards/'
    | '/boards/$boardId/archive'
    | '/boards/$boardId/canvas'
    | '/boards/$boardId/docs'
    | '/boards/$boardId/htmldocs'
    | '/boards/$boardId/secrets'
    | '/boards/$boardId/webhooks'
    | '/boards/$boardId/'
    | '/boards/$boardId/canvas/$canvasId'
    | '/boards/$boardId/cards/$cardSlug'
    | '/boards/$boardId/docs/$docId'
    | '/boards/$boardId/htmldocs/$htmlDocId'
    | '/boards/$boardId/archive/'
    | '/boards/$boardId/canvas/'
    | '/boards/$boardId/docs/'
    | '/boards/$boardId/htmldocs/'
    | '/boards/$boardId/secrets/'
    | '/boards/$boardId/webhooks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardsRoute: typeof BoardsRouteWithChildren
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  TimeRoute: typeof TimeRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/time': {
      id: '/time'
      path: '/time'
      fullPath: '/time'
      preLoaderRoute: typeof TimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards': {
      id: '/boards'
      path: '/boards'
      fullPath: '/boards'
      preLoaderRoute: typeof BoardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards/': {
      id: '/boards/'
      path: '/'
      fullPath: '/boards/'
      preLoaderRoute: typeof BoardsIndexRouteImport
      parentRoute: typeof BoardsRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards/$boardId': {
      id: '/boards/$boardId'
      path: '/$boardId'
      fullPath: '/boards/$boardId'
      preLoaderRoute: typeof BoardsBoardIdRouteImport
      parentRoute: typeof BoardsRoute
    }
    '/boards/$boardId/': {
      id: '/boards/$boardId/'
      path: '/'
      fullPath: '/boards/$boardId/'
      preLoaderRoute: typeof BoardsBoardIdIndexRouteImport
      parentRoute: typeof BoardsBoardIdRoute
    }
    '/boards/$boardId/webhooks': {
      id: '/boards/$boardId/webhooks'
      path: '/webhooks'
      fullPath: '/boards/$boardId/webhooks'
      preLoaderRoute: typeof BoardsBoardIdWebhooksRouteImport
      parentRoute: typeof BoardsBoardIdRoute
    }
    '/boards/$boardId/secrets': {
      id: '/boards/$boardId/secrets'
      path: '/secrets'
      fullPath: '/boards/$boardId/secrets'
      preLoaderRoute: typeof BoardsBoardIdSecretsRouteImport
      parentRoute: typeof BoardsBoardIdRoute
    }
    '/boards/$boardId/htmldocs': {
      id: '/boards/$boardId/htmldocs'
      path: '/htmldocs'
      fullPath: '/boards/$boardId/htmldocs'
      preLoaderRoute: typeof BoardsBoardIdHtmldocsRouteImport
      parentRoute: typeof BoardsBoardIdRoute
    }
    '/boards/$boardId/docs': {
      id: '/boards/$boardId/docs'
      path: '/docs'
      fullPath: '/boards/$boardId/docs'
      preLoaderRoute: typeof BoardsBoardIdDocsRouteImport
      parentRoute: typeof BoardsBoardIdRoute
    }
    '/boards/$boardId/canvas': {
      id: '/boards/$boardId/canvas'
      path: '/canvas'
      fullPath: '/boards/$boardId/canvas'
      preLoaderRoute: typeof BoardsBoardIdCanvasRouteImport
      parentRoute: typeof BoardsBoardIdRoute
    }
    '/boards/$boardId/archive': {
      id: '/boards/$boardId/archive'
      path: '/archive'
      fullPath: '/boards/$boardId/archive'
      preLoaderRoute: typeof BoardsBoardIdArchiveRouteImport
      parentRoute: typeof BoardsBoardIdRoute
    }
    '/boards/$boardId/webhooks/': {
      id: '/boards/$boardId/webhooks/'
      path: '/'
      fullPath: '/boards/$boardId/webhooks/'
      preLoaderRoute: typeof BoardsBoardIdWebhooksIndexRouteImport
      parentRoute: typeof BoardsBoardIdWebhooksRoute
    }
    '/boards/$boardId/secrets/': {
      id: '/boards/$boardId/secrets/'
      path: '/'
      fullPath: '/boards/$boardId/secrets/'
      preLoaderRoute: typeof BoardsBoardIdSecretsIndexRouteImport
      parentRoute: typeof BoardsBoardIdSecretsRoute
    }
    '/boards/$boardId/htmldocs/': {
      id: '/boards/$boardId/htmldocs/'
      path: '/'
      fullPath: '/boards/$boardId/htmldocs/'
      preLoaderRoute: typeof BoardsBoardIdHtmldocsIndexRouteImport
      parentRoute: typeof BoardsBoardIdHtmldocsRoute
    }
    '/boards/$boardId/docs/': {
      id: '/boards/$boardId/docs/'
      path: '/'
      fullPath: '/boards/$boardId/docs/'
      preLoaderRoute: typeof BoardsBoardIdDocsIndexRouteImport
      parentRoute: typeof BoardsBoardIdDocsRoute
    }
    '/boards/$boardId/canvas/': {
      id: '/boards/$boardId/canvas/'
      path: '/'
      fullPath: '/boards/$boardId/canvas/'
      preLoaderRoute: typeof BoardsBoardIdCanvasIndexRouteImport
      parentRoute: typeof BoardsBoardIdCanvasRoute
    }
    '/boards/$boardId/archive/': {
      id: '/boards/$boardId/archive/'
      path: '/'
      fullPath: '/boards/$boardId/archive/'
      preLoaderRoute: typeof BoardsBoardIdArchiveIndexRouteImport
      parentRoute: typeof BoardsBoardIdArchiveRoute
    }
    '/boards/$boardId/htmldocs/$htmlDocId': {
      id: '/boards/$boardId/htmldocs/$htmlDocId'
      path: '/$htmlDocId'
      fullPath: '/boards/$boardId/htmldocs/$htmlDocId'
      preLoaderRoute: typeof BoardsBoardIdHtmldocsHtmlDocIdRouteImport
      parentRoute: typeof BoardsBoardIdHtmldocsRoute
    }
    '/boards/$boardId/docs/$docId': {
      id: '/boards/$boardId/docs/$docId'
      path: '/$docId'
      fullPath: '/boards/$boardId/docs/$docId'
      preLoaderRoute: typeof BoardsBoardIdDocsDocIdRouteImport
      parentRoute: typeof BoardsBoardIdDocsRoute
    }
    '/boards/$boardId/cards/$cardSlug': {
      id: '/boards/$boardId/cards/$cardSlug'
      path: '/cards/$cardSlug'
      fullPath: '/boards/$boardId/cards/$cardSlug'
      preLoaderRoute: typeof BoardsBoardIdCardsCardSlugRouteImport
      parentRoute: typeof BoardsBoardIdRoute
    }
    '/boards/$boardId/canvas/$canvasId': {
      id: '/boards/$boardId/canvas/$canvasId'
      path: '/$canvasId'
      fullPath: '/boards/$boardId/canvas/$canvasId'
      preLoaderRoute: typeof BoardsBoardIdCanvasCanvasIdRouteImport
      parentRoute: typeof BoardsBoardIdCanvasRoute
    }
  }
}

interface BoardsBoardIdArchiveRouteChildren {
  BoardsBoardIdArchiveIndexRoute: typeof BoardsBoardIdArchiveIndexRoute
}

const BoardsBoardIdArchiveRouteChildren: BoardsBoardIdArchiveRouteChildren = {
  BoardsBoardIdArchiveIndexRoute: BoardsBoardIdArchiveIndexRoute,
}

const BoardsBoardIdArchiveRouteWithChildren =
  BoardsBoardIdArchiveRoute._addFileChildren(BoardsBoardIdArchiveRouteChildren)

interface BoardsBoardIdCanvasRouteChildren {
  BoardsBoardIdCanvasCanvasIdRoute: typeof BoardsBoardIdCanvasCanvasIdRoute
  BoardsBoardIdCanvasIndexRoute: typeof BoardsBoardIdCanvasIndexRoute
}

const BoardsBoardIdCanvasRouteChildren: BoardsBoardIdCanvasRouteChildren = {
  BoardsBoardIdCanvasCanvasIdRoute: BoardsBoardIdCanvasCanvasIdRoute,
  BoardsBoardIdCanvasIndexRoute: BoardsBoardIdCanvasIndexRoute,
}

const BoardsBoardIdCanvasRouteWithChildren =
  BoardsBoardIdCanvasRoute._addFileChildren(BoardsBoardIdCanvasRouteChildren)

interface BoardsBoardIdDocsRouteChildren {
  BoardsBoardIdDocsDocIdRoute: typeof BoardsBoardIdDocsDocIdRoute
  BoardsBoardIdDocsIndexRoute: typeof BoardsBoardIdDocsIndexRoute
}

const BoardsBoardIdDocsRouteChildren: BoardsBoardIdDocsRouteChildren = {
  BoardsBoardIdDocsDocIdRoute: BoardsBoardIdDocsDocIdRoute,
  BoardsBoardIdDocsIndexRoute: BoardsBoardIdDocsIndexRoute,
}

const BoardsBoardIdDocsRouteWithChildren =
  BoardsBoardIdDocsRoute._addFileChildren(BoardsBoardIdDocsRouteChildren)

interface BoardsBoardIdHtmldocsRouteChildren {
  BoardsBoardIdHtmldocsHtmlDocIdRoute: typeof BoardsBoardIdHtmldocsHtmlDocIdRoute
  BoardsBoardIdHtmldocsIndexRoute: typeof BoardsBoardIdHtmldocsIndexRoute
}

const BoardsBoardIdHtmldocsRouteChildren: BoardsBoardIdHtmldocsRouteChildren = {
  BoardsBoardIdHtmldocsHtmlDocIdRoute: BoardsBoardIdHtmldocsHtmlDocIdRoute,
  BoardsBoardIdHtmldocsIndexRoute: BoardsBoardIdHtmldocsIndexRoute,
}

const BoardsBoardIdHtmldocsRouteWithChildren =
  BoardsBoardIdHtmldocsRoute._addFileChildren(
    BoardsBoardIdHtmldocsRouteChildren,
  )

interface BoardsBoardIdSecretsRouteChildren {
  BoardsBoardIdSecretsIndexRoute: typeof BoardsBoardIdSecretsIndexRoute
}

const BoardsBoardIdSecretsRouteChildren: BoardsBoardIdSecretsRouteChildren = {
  BoardsBoardIdSecretsIndexRoute: BoardsBoardIdSecretsIndexRoute,
}

const BoardsBoardIdSecretsRouteWithChildren =
  BoardsBoardIdSecretsRoute._addFileChildren(BoardsBoardIdSecretsRouteChildren)

interface BoardsBoardIdWebhooksRouteChildren {
  BoardsBoardIdWebhooksIndexRoute: typeof BoardsBoardIdWebhooksIndexRoute
}

const BoardsBoardIdWebhooksRouteChildren: BoardsBoardIdWebhooksRouteChildren = {
  BoardsBoardIdWebhooksIndexRoute: BoardsBoardIdWebhooksIndexRoute,
}

const BoardsBoardIdWebhooksRouteWithChildren =
  BoardsBoardIdWebhooksRoute._addFileChildren(
    BoardsBoardIdWebhooksRouteChildren,
  )

interface BoardsBoardIdRouteChildren {
  BoardsBoardIdArchiveRoute: typeof BoardsBoardIdArchiveRouteWithChildren
  BoardsBoardIdCanvasRoute: typeof BoardsBoardIdCanvasRouteWithChildren
  BoardsBoardIdDocsRoute: typeof BoardsBoardIdDocsRouteWithChildren
  BoardsBoardIdHtmldocsRoute: typeof BoardsBoardIdHtmldocsRouteWithChildren
  BoardsBoardIdSecretsRoute: typeof BoardsBoardIdSecretsRouteWithChildren
  BoardsBoardIdWebhooksRoute: typeof BoardsBoardIdWebhooksRouteWithChildren
  BoardsBoardIdIndexRoute: typeof BoardsBoardIdIndexRoute
  BoardsBoardIdCardsCardSlugRoute: typeof BoardsBoardIdCardsCardSlugRoute
}

const BoardsBoardIdRouteChildren: BoardsBoardIdRouteChildren = {
  BoardsBoardIdArchiveRoute: BoardsBoardIdArchiveRouteWithChildren,
  BoardsBoardIdCanvasRoute: BoardsBoardIdCanvasRouteWithChildren,
  BoardsBoardIdDocsRoute: BoardsBoardIdDocsRouteWithChildren,
  BoardsBoardIdHtmldocsRoute: BoardsBoardIdHtmldocsRouteWithChildren,
  BoardsBoardIdSecretsRoute: BoardsBoardIdSecretsRouteWithChildren,
  BoardsBoardIdWebhooksRoute: BoardsBoardIdWebhooksRouteWithChildren,
  BoardsBoardIdIndexRoute: BoardsBoardIdIndexRoute,
  BoardsBoardIdCardsCardSlugRoute: BoardsBoardIdCardsCardSlugRoute,
}

const BoardsBoardIdRouteWithChildren = BoardsBoardIdRoute._addFileChildren(
  BoardsBoardIdRouteChildren,
)

interface BoardsRouteChildren {
  BoardsBoardIdRoute: typeof BoardsBoardIdRouteWithChildren
  BoardsIndexRoute: typeof BoardsIndexRoute
}

const BoardsRouteChildren: BoardsRouteChildren = {
  BoardsBoardIdRoute: BoardsBoardIdRouteWithChildren,
  BoardsIndexRoute: BoardsIndexRoute,
}

const BoardsRouteWithChildren =
  BoardsRoute._addFileChildren(BoardsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardsRoute: BoardsRouteWithChildren,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  TimeRoute: TimeRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
